### ISSUE TITLE
curl usage for api-server

### ISSUE THREAD

**Issue by jrsmile** [ffplayout/ffplayout-messenger#2]
Hi, i cant figure out how to use the client and the api server, at first i thought you have to use both the api server and the client.
but i figured the client can directly communicate with the zmq server.

but when testing with curl -H "Content-Type: application/json" -u user:password -d @scrolling-text.json http://stream-mgmt.example.com:8888 -v 

i always get:
`
 TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x5625322cef50)
* Connected to stream-mgmt.example.com (ip.ip.ip.ip) port 8888 (#0)
* Server auth using Basic with user 'user'
> POST / HTTP/1.1
> Host: stream-mgmt.example.com:8888
> Authorization: Basic <BASICAUTHPW>
> User-Agent: curl/7.64.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 329
> 
* upload completely sent off: 329 out of 329 bytes
< HTTP/1.1 200 OK
< Content-Type: application/json
< Server: 
< Date: Fri, 28 Aug 2020 10:12:59 GMT
< Allow: DELETE, GET, HEAD, POST, PUT
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: POST
< Access-Control-Allow-Headers: Cache-Control,X-Proxy-Authorization,X-Requested-With,Content-Type
< Content-Length: 22
< Set-Cookie: session_id=2f947742ccace573c8b610b94d8340c2fd0a16d0; expires=Fri, 28 Aug 2020 11:12:59 GMT; Max-Age=3600; Path=/
< 
* Connection #0 to host stream-mgmt.example.com left intact
"{\"Success\": false}"
`
could you please explain how to use the api-server.py

**Comment by jrsmile** [comment]
nevermind had to add user and password to the json file and wrap the rest in data field.

**Comment by jb-alvarado** [comment]
Hi, the code from this messenger is not good maintained any more, because I have integrate this functionality in [ffplayout-gui](https://github.com/ffplayout/ffplayout-gui)

**Comment by jb-alvarado** [comment]
I migrate the GUI now to ffplayout-api to
